// src/constants/contentKinds.js
// Single source of truth for the four "Explore Faith" Home-screen sections
// (Bible / Jesus / Prayers / Worship). Everything that differs between the
// four — which Firestore collection to read, which like/dislike/save/view
// functions to call, cache keys, copy, and accent color — lives here so the
// screen, card, and detail components can stay generic instead of being
// copy-pasted four times.
import { STORAGE_KEYS } from './index';
import { LIBRARY_ACCENTS } from './library';
import {
  subscribeToBibleCarousel,
  subscribeToBibleContent,
  fetchBibleContentById,
  fetchRelatedBibleContent,
  getUserBibleInteraction,
  toggleBibleLike,
  toggleBibleDislike,
  registerBibleView,
  isBibleContentSaved,
  toggleSaveBibleContent,
  subscribeToSavedBibleContent,
  subscribeToJesusCarousel,
  subscribeToJesusContent,
  fetchJesusContentById,
  fetchRelatedJesusContent,
  getUserJesusInteraction,
  toggleJesusLike,
  toggleJesusDislike,
  registerJesusView,
  isJesusContentSaved,
  toggleSaveJesusContent,
  subscribeToSavedJesusContent,
  subscribeToPrayersCarousel,
  subscribeToPrayersContent,
  fetchPrayersContentById,
  fetchRelatedPrayersContent,
  getUserPrayersInteraction,
  togglePrayersLike,
  togglePrayersDislike,
  registerPrayersView,
  isPrayersContentSaved,
  toggleSavePrayersContent,
  subscribeToSavedPrayersContent,
  subscribeToWorshipCarousel,
  subscribeToWorshipContent,
  fetchWorshipContentById,
  fetchRelatedWorshipContent,
  getUserWorshipInteraction,
  toggleWorshipLike,
  toggleWorshipDislike,
  registerWorshipView,
  isWorshipContentSaved,
  toggleSaveWorshipContent,
  subscribeToSavedWorshipContent,
} from '../services/firebaseService';

export const CONTENT_KINDS = {
  bible: {
    key: 'bible',
    label: 'Bible',
    // Home screen's "Explore Faith" row already calls this section "Gospel"
    // (see theme/homeTheme.js STORY_CATEGORIES) — the in-screen heading now
    // matches so the label doesn't change between tapping in and arriving.
    headerTitle: 'Gospel',
    headerSubtitle: 'Life of Jesus',
    accent: LIBRARY_ACCENTS.bible,
    // Pure visual gallery: cover image only, no title/description/actions
    // on the listing itself — see components/library/FaithGalleryCard.js.
    // Tapping a tile opens the full reading experience on ContentDetail.
    cardVariant: 'gallery',
    gridColumns: 2,
    emptyIcon: 'book-outline',
    emptyTitle: 'No content yet',
    emptyMessage: 'Check back soon for new Bible content.',
    storageKeyCarousel: STORAGE_KEYS.LIBRARY_CACHE_BIBLE_CAROUSEL,
    storageKeyContent: STORAGE_KEYS.LIBRARY_CACHE_BIBLE_CONTENT,
    subscribeCarousel: subscribeToBibleCarousel,
    subscribeContent: subscribeToBibleContent,
    fetchContentById: fetchBibleContentById,
    fetchRelated: fetchRelatedBibleContent,
    getUserInteraction: getUserBibleInteraction,
    toggleLike: toggleBibleLike,
    toggleDislike: toggleBibleDislike,
    registerView: registerBibleView,
    isSaved: isBibleContentSaved,
    toggleSave: toggleSaveBibleContent,
    subscribeSaved: subscribeToSavedBibleContent,
  },
  jesus: {
    key: 'jesus',
    label: 'Jesus',
    // Home row calls this section "Heroes".
    headerTitle: 'Heroes',
    headerSubtitle: 'Faithful Champions',
    accent: LIBRARY_ACCENTS.jesus,
    cardVariant: 'gallery',
    gridColumns: 2,
    emptyIcon: 'heart-outline',
    emptyTitle: 'No content yet',
    emptyMessage: 'Check back soon for new content about Jesus.',
    storageKeyCarousel: STORAGE_KEYS.LIBRARY_CACHE_JESUS_CAROUSEL,
    storageKeyContent: STORAGE_KEYS.LIBRARY_CACHE_JESUS_CONTENT,
    subscribeCarousel: subscribeToJesusCarousel,
    subscribeContent: subscribeToJesusContent,
    fetchContentById: fetchJesusContentById,
    fetchRelated: fetchRelatedJesusContent,
    getUserInteraction: getUserJesusInteraction,
    toggleLike: toggleJesusLike,
    toggleDislike: toggleJesusDislike,
    registerView: registerJesusView,
    isSaved: isJesusContentSaved,
    toggleSave: toggleSaveJesusContent,
    subscribeSaved: subscribeToSavedJesusContent,
  },
  prayers: {
    key: 'prayers',
    label: 'Prayer',
    // Home row calls this section "Prophets".
    headerTitle: 'Prophets',
    headerSubtitle: "God's Messengers",
    accent: LIBRARY_ACCENTS.prayers,
    cardVariant: 'gallery',
    gridColumns: 2,
    emptyIcon: 'hand-left-outline',
    emptyTitle: 'No content yet',
    emptyMessage: 'Check back soon for new prayer content.',
    storageKeyCarousel: STORAGE_KEYS.LIBRARY_CACHE_PRAYERS_CAROUSEL,
    storageKeyContent: STORAGE_KEYS.LIBRARY_CACHE_PRAYERS_CONTENT,
    subscribeCarousel: subscribeToPrayersCarousel,
    subscribeContent: subscribeToPrayersContent,
    fetchContentById: fetchPrayersContentById,
    fetchRelated: fetchRelatedPrayersContent,
    getUserInteraction: getUserPrayersInteraction,
    toggleLike: togglePrayersLike,
    toggleDislike: togglePrayersDislike,
    registerView: registerPrayersView,
    isSaved: isPrayersContentSaved,
    toggleSave: toggleSavePrayersContent,
    subscribeSaved: subscribeToSavedPrayersContent,
  },
  worship: {
    key: 'worship',
    label: 'Worship',
    // Home row calls this section "Kings". No exact subtitle copy was given
    // for this one (the request specified Gospel/Heroes/Prophets only) —
    // "Anointed Rulers" is a placeholder in the same short-epithet style as
    // the other three. Easy one-line change in this file if different copy
    // is wanted.
    headerTitle: 'Kings',
    headerSubtitle: 'Anointed Rulers',
    accent: LIBRARY_ACCENTS.worship,
    cardVariant: 'gallery',
    gridColumns: 2,
    emptyIcon: 'musical-notes-outline',
    emptyTitle: 'No content yet',
    emptyMessage: 'Check back soon for new worship content.',
    storageKeyCarousel: STORAGE_KEYS.LIBRARY_CACHE_WORSHIP_CAROUSEL,
    storageKeyContent: STORAGE_KEYS.LIBRARY_CACHE_WORSHIP_CONTENT,
    subscribeCarousel: subscribeToWorshipCarousel,
    subscribeContent: subscribeToWorshipContent,
    fetchContentById: fetchWorshipContentById,
    fetchRelated: fetchRelatedWorshipContent,
    getUserInteraction: getUserWorshipInteraction,
    toggleLike: toggleWorshipLike,
    toggleDislike: toggleWorshipDislike,
    registerView: registerWorshipView,
    isSaved: isWorshipContentSaved,
    toggleSave: toggleSaveWorshipContent,
    subscribeSaved: subscribeToSavedWorshipContent,
  },
};

export const getContentKindConfig = (kind) => CONTENT_KINDS[kind] || null;
